posts/urls.py
from django.urls import path
from . import views

app_name='posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('listings', views.listings, name='listings'),
    path('details/<int:pk>', views.details, name='details'),
    path('create', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

simpleCrud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.utils import timezone
#from django.contrib.auth import settings
# Create your models here.
class PostModel(models.Model):
    #author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    image = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from .models import PostModel
class PostForm(forms.ModelForm):
    
    class Meta:
        model = PostModel
        fields = ('title','image', 'content')
        labels = {
            'title':"Article",
            'content':'Content'
        }
        widgets = {
            'title' : forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'titre'
                      }),
            'content' : forms.Textarea(attrs={
                    'class': 'form-control',
                    'placeholder': 'contenu'
                    }),
        }

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import PostModel
from .forms import PostForm
# Create your views here.
def index(request):
    posts = PostModel.objects.all()[:3]
    return render(request, 'posts/index.html', {'posts':posts})

def listings(request):
    posts = PostModel.objects.all()
    return render(request, 'posts/listings.html', {'posts':posts})

def details(request, pk):
    post = get_object_or_404(PostModel, pk=pk)
    return render(request, 'posts/details.html', {'post':post})

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:listings')
        else:
            form = PostForm(request.POST)
            return render(request, 'posts/create.html', {'form':form})
    else:
        form = PostForm()
        return render(request, 'posts/create.html', {'form':form})

def update(request, pk):
    post = get_object_or_404(PostModel, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            form.save(commit=False)
            form.save()
            return redirect('posts:listings')
    else:
        form = PostForm(instance=post)
        return render(request, 'posts/update.html', {'post':post, 'form':form})

def delete(request, pk):
    post = get_object_or_404(PostModel, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('posts:listings')
    return render(request, 'posts/delete.html', {'post':post})

posts/templates/posts/create.html
{% extends "./partials/base.html" %}
{% block content %}
  <h1>Publier un article</h1>
  <div class="container">
    <div class="row">
      <div class="mr-auto">
        <form  action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
          {{form.as_p}} 
        <input type="submit" value="publier" class="btn btn-success">
      </form>
      </div>
    </div>
  </div>
{% endblock content %}

posts/templates/posts/delete.html
{% extends "./partials/base.html" %}
{% block content %}
  <h1>suppimer un article </h1>
  <p>voullez vous supprimer cette article <strong>{{post.title}}</strong>  
    <div class="row">
      <form class="col-3" action="{% url 'posts:delete' post.id %}" method="post">
        {% csrf_token %}
        <input class="btn btn-lg btn-danger " type="submit" value="Oui"> 
      </form> 
      <a class="btn btn-lg btn-warning " href="{% url 'posts:details' post.id %}">Non</a>
    </div>
  </p>
{% endblock content %}

posts/templates/posts/details.html
{% extends "./partials/base.html" %}
{% block content %}
<div class="container mt-4">
  <h1 class="col-12">details de l'article</h1>
  <div class="col-12">
    <h2 id="title-details" >{{post.title}}</h2>
  </div>
  <div class="col-12">
    <img src="{{post.image.url}}" alt="{{post.image}}" class="img img-fluid mx-auto d-block"> <br>
  </div>
  <div class="col-12">
     <p class="bg-light">{{post.content}}</p>
  </div>
  <div class="col-12">
    <p>
      publier {{post.created}} <br> modifier il y'a {{post.modified|timesince}}
    </p>
  </div>
    <div class="col-12 ">
      <a class="btn btn-primary" href="{% url 'posts:update' post.id %} ">modifier</a> <a class="btn btn-danger" href="{% url 'posts:delete' post.id %}"> Supprimer</a>
    </div>
  </div>
</div>
{% endblock content %}

posts/templates/posts/index.html
{% extends "./partials/base.html" %}
{% block content %}
  <h1>Page d'accueil</h1>
  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quasi culpa natus rem incidunt dolorum odio. Quis voluptate porro doloribus veritatis quam illum sed saepe culpa eligendi, ab, ducimus in?</p>
  
  <div class="row mt-4">
   {% for post in posts %}
      <div class="col-sm-3">
        <p><a href="{% url 'posts:details' post.id %}"><img src="{{post.image.url}}" alt="{{post.image}}" class="img rounded-circle" width="180" height="180"></a>  </p>
        <h3>{{post.title}}</h3>
        <p>{{post.content|truncatewords:10}} ...</p>
      </div>
  {% endfor %}
  </div>
  <p><a class="btn  btn-dark" href="{% url 'posts:listings' %}">Plus d'articles &raquo;</a></p>
{% endblock content %}

posts/templates/posts/listings.html
{% extends "./partials/base.html" %}
{% block content %}
 <div class="row mt-4">
   {% for post in posts %}
      <div class="col-md-4 col-sm-2">
        <p><a href="{% url 'posts:details' post.id %}"><img src="{{post.image.url}}" alt="{{post.image}}" class="img img-thumbnail" width="250" height="250"></a>  </p>
        <h3>{{post.title}}</h3>
        <p >{{post.content|truncatewords:10}} ... <a class="btn btn-dark" href="{% url 'posts:details' post.id %}">voir les détails</a></p>
      </div>
      {%empty%}
      <h3 class="text-center">Aucun article n'est  actuellement  disponible</h3>
  {% endfor %}
  </div>
{% endblock content %}

posts/templates/posts/partials/_nav.html
<nav  class="navbar navbar-expand-lg  navbar-light bg-dark ">
    <a class="navbar-brand " id='navbar-brand' href="{% url 'posts:index' %}">Simple CRUD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menuTogle" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon bg-primary"></span>
    </button>
    <div class="collapse navbar-collapse" id="menuTogle">
        <ul class="navbar-nav mr-auto ">
            <li class="nav-item {% if request.path == '/'  %} active {% endif %}">
                <a class="nav-link " href="{% url 'posts:index' %}">Accueil</a>
            </li>
            <li class="nav-item{% if 'listings' in request.path %} active {% endif %} ">
                <a class="nav-link " href="{% url 'posts:listings' %}" >Liste des Articles</a>
            </li>
            <li class="nav-item{% if 'create' in request.path %} active {% endif %} ">
                <a class="nav-link " href="{% url 'posts:create' %}" >Publier un article</a>
            </li>
        </ul>
    </div>
</nav>

posts/templates/posts/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Bootstrap cnd-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--Comment bootstrap css-->
    {% comment %}
      <link rel="stylesheet" href="{% static 'posts/css/bootstrap.min.css' %}">
    {% endcomment %}
    <!--End comment bootstrap-->
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'posts/css/main.css' %}">
    <title>{% block title %}Simple CRUD{% endblock title %}</title>
</head>
<body>
    <div class="container-fluid">
        {% include "./_nav.html" %}
        {% block content %}
        
        {% endblock content %}
        <div class="mt-5 text-center ">
            {% include "./footer.html" %}
        </div>
    </div>

    <!--comment static files for local -->
    {% comment %}
        <script src="{% static 'posts/js/jquery-3.4.1.js' %}"></script>
        <script src="{% static 'posts/js/bootstrap.min.js' %}"></script>
    {% endcomment %}
    <!--end comment static-->

    <!--Jquery and bootstrap js cdn-->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            
</body>
</html>

posts/templates/posts/partials/footer.html
<footer>
    <p>&copy; Copyright all rights reserved {% now 'Y' %} !</p>
</footer>

posts/templates/posts/update.html
{% extends "./partials/base.html" %}
{% block content %}
  <h1>modifier un article</h1>
  <div class="row">
    <form class="form-group " action="{% url 'posts:update' post.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="modifier" class="btn btn-success">
    </form>
  </div>
{% endblock content %}